version: '3.1'

services:
  mysql:
    image: mysql
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
     - 3306:3306
    networks:
      cidar-api-network:
        ipv4_address: 172.26.0.2

  node-application:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: node-application
    working_dir: /app
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=Total
      - DB_USERNAME=root
      - DB_PASSWORD=root
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - mysql
    networks:
      cidar-api-network:
        ipv4_address: 172.26.0.3

  web:
    image: nginx
    volumes:
     - ./templates:/usr/share/nginx/html
    ports:
      - "8000:80"
    depends_on:
      - mysql  


networks:
  cidar-api-network:
    name: cidar-api-network
    driver: bridge
    ipam:
      config:
        - subnet: 172.26.0.0/16